# Generated by Django 4.0.6 on 2023-04-16 07:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('BakersApp', '0003_themecakes'),
    ]

    operations = [
        migrations.AddField(
            model_name='anniversarycakes',
            name='Cake_Flavour',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='birthdaycakes',
            name='Cake_Flavour',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='themecakes',
            name='Cake_Flavour',
            field=models.CharField(default=' ', max_length=1000),
            preserve_default=False,
        ),
    ]
