# Generated by Django 4.0.6 on 2023-04-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakersApp', '0006_cart_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cake_Image', models.FileField(max_length=1000, upload_to='')),
                ('Cake_Name', models.CharField(max_length=1000)),
                ('Cake_Price', models.IntegerField()),
                ('Cake_Review', models.IntegerField()),
                ('Cake_Flavour', models.CharField(max_length=1000)),
                ('category', models.IntegerField(max_length=10)),
            ],
        ),
    ]
