# Generated by Django 4.0.6 on 2023-04-30 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakersApp', '0008_alter_cakes_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Cake_Image',
            field=models.FileField(default='', max_length=1000, upload_to=''),
            preserve_default=False,
        ),
    ]
