# Generated by Django 4.0.6 on 2023-04-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakersApp', '0009_cart_cake_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Cake_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
