# Generated by Django 4.0.6 on 2023-04-30 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BakersApp', '0010_cart_cake_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Cake_id',
            new_name='Cid',
        ),
    ]
