# Generated by Django 4.0.6 on 2023-04-30 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakersApp', '0012_remove_cart_cid'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Cake_flavour',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
