# Generated by Django 4.0.6 on 2023-05-02 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakersApp', '0013_cart_cake_flavour'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video_Title', models.CharField(max_length=1000)),
                ('Video_File', models.FileField(upload_to='')),
                ('Video_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
