# Generated by Django 4.0.6 on 2023-05-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakersApp', '0014_tutorialvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialvideo',
            name='Video_Thumbnail',
            field=models.FileField(default='', max_length=500, upload_to=''),
            preserve_default=False,
        ),
    ]
