# Generated by Django 4.0.6 on 2023-05-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakersApp', '0015_tutorialvideo_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorialvideo',
            name='Video_description',
            field=models.TextField(max_length=1000),
        ),
    ]
