# Generated by Django 4.0.6 on 2023-08-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakersApp', '0017_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='CakeId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
