# Generated by Django 4.0.6 on 2023-08-08 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BakersApp', '0018_cart_cakeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakes',
            name='Cake_Image',
            field=models.FileField(upload_to=''),
        ),
    ]
